### ISSUE TITLE
--rev-version flag is broken

### ISSUE THREAD

**Issue by xinyi-joffre** [microsoft/tfs-cli#358]
I am using version 0.8.3 of tfx. When using the command `tfx extension create --rev-version`, I get the following error message:

```
error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Inplace
```

It looks like it is an error with the json parsing and writing. 

I'm happy to take a look and find a fix.

**Comment by VAllens** [comment]
```
TFS Cross Platform Command Line Interface v0.8.3
Copyright Microsoft Corporation
error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Inplace
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
```

This error only occurs in node v14.x or above

**Comment by dwilsonactual** [comment]
Fixed in 0.9.0, thanks for the PR, @xinyi-joffre

**Comment by VAllens** [comment]
Good!!! 👍

**Comment by abhi-msft** [comment]
Issue still exists for tfx cli v0.9.2 when using node v14.17.1

**Comment by KumailP** [comment]
Happening to me on tfx cli v0.9.3 and node v14.16.0
