### ISSUE TITLE
tfx extension create failed from package script

### ISSUE THREAD

**Issue by NadavShaked** [microsoft/tfs-cli#397]
I'm using this package to compile and build my extension

`{
  "id": "extensionAzureDevOps",
  "name": "extension",
  "publisher": "ME",
  "version": "0.0.63",
  "description": "Azure DevOps Extension",
  "keywords": [
    "extensions",
    "Azure DevOps",
    "Visual Studio Team Services"
  ],
  "engines": {
    "vscode": "^1.8.0"
  },
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "clean": "rimraf ./dist",
    "compile": "npm run clean && npm run test && webpack --mode production",
    "compile:dev": "npm run clean && npm run test && webpack --mode development",
    "build": "npm run compile",
    "build:dev": "npm run compile:dev && npm run postbuild",
    "postbuild": "npm run package-extension -- --rev-version",
    "package-extension": "tfx extension create --manifest-globs azure-devops-extension.json src/TabExtension/*.json",
    "publish-extension": "tfx extension publish --manifest-globs azure-devops-extension.json src/TabExtension/*.json",
    "test": "set TEST_REPORT_FILENAME=test-results.xml && jest --verbose"
  },
  "dependencies": {
    "@fluentui/react": "^8.36.3",
    "azure-devops-extension-api": "~1.157.0",
    "azure-devops-extension-sdk": "~2.0.11",
    "azure-devops-ui": "~2.164.0",
    "react": "~16.13.1",
    "react-dom": "~16.13.1"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.11.0",
    "@testing-library/react": "^10.4.4",
    "@types/jest": "^26.0.3",
    "@types/react": "~16.8.2",
    "@types/react-dom": "~16.8.0",
    "copy-webpack-plugin": "^7.0.0",
    "base64-inline-loader": "~1.1.1",
    "css-loader": "~1.0.0",
    "jest": "^26.1.0",
    "jest-junit-reporter": "^1.1.0",
    "node-sass": "^5.0.0",
    "rimraf": "~2.6.2",
    "sass-loader": "~10.0.5",
    "style-loader": "~0.23.1",
    "tfx-cli": "^0.6.3",
    "ts-jest": "^26.1.1",
    "ts-loader": "~5.2.2",
    "typescript": "^3.9.6",
    "webpack": "^5.23.0",
    "webpack-cli": "^4.5.0"
  },
  "jest": {
    "transform": {
      "^.+\\.(js|ts|tsx|jsx)$": "ts-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|azure-devops-ui|azure-devops-extension-sdk)/)"
    ],
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/__mocks__/fileMock.js",
      "\\.(css|less|scss)$": "<rootDir>/src/__mocks__/styleMock.js"
    },
    "preset": "ts-jest/presets/js-with-babel",
    "testResultsProcessor": "./node_modules/jest-junit-reporter",
    "collectCoverage": true,
    "coverageReporters": [
      "json",
      "html",
      "cobertura"
    ],
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.test.json"
      }
    }
  }
}`

When I run the command `npm run postbuild`, I receive this error:

tfx extension create --manifest-globs azure-devops-extension.json src/TabExtension/*.json "--rev-version"

(node:89172) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
TFS Cross Platform Command Line Interface v0.6.4
Copyright Microsoft Corporation
error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Inplace
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! feedback-extension-for-azuredevops@0.0.63 package-extension: `tfx extension create --manifest-globs azure-devops-extension.json src/TabExtension/*.json "--rev-version"`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the feedback-extension-for-azuredevops@0.0.63 package-extension script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\t-nashak\AppData\Roaming\npm-cache\_logs\2021-12-08T15_15_13_712Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! feedback-extension-for-azuredevops@0.0.63 postbuild: `npm run package-extension -- --rev-version`
npm ERR! Exit status 4294967295
npm ERR!

But when I run the command `tfx extension create --manifest-globs azure-devops-extension.json src/TabExtension/*.json --rev-version` it works well

what causes the dependencies cycle? how can I fix it?

note: if I remove the param --rev-version it will work well

**Comment by nawok** [comment]
Hi @NadavShaked, according to #358 this was fixed in version 0.9.0. You are still using version 0.6.3 in your `devDependencies`.

**Comment by kirill-ivlev** [comment]
Hi @NadavShaked were you able to fix this issue by updating tfx-cli or this issue is still actual for you?

**Comment by kirill-ivlev** [comment]
Closing this issue due to inactivity, please in case this problem is still actual for you open a new one.
